### ISSUE TITLE
How to configure Controls

### ISSUE THREAD

**Issue by kolman** [pixtron/storybook-addon-docs-stencil#5] opened 2021-05-25 20:14 UTC
This addon is awesome and works well for the description and args table in the storybook docs. However, the "Controls" panel in the storybook canvas does not work. Is there any configuration I am missing?

I have the following config in preview.js:

```
if (docJson) setStencilDocJson(docJson);

export const parameters = {
  controls: { hideNoControlsWarning: true },
  docs: {
    extractArgTypes,
    extractComponentDescription,
  },
};
```

I found the following workaround. If I use `extractArgTypes` directly in the story Meta tag, it works (my-button.stories.mdx):

```
import { extractArgTypes } from '@pxtrn/storybook-addon-docs-stencil';

<Meta 
  title="Components/Button" 
  component="my-button" 
  argTypes={extractArgTypes('my-button')} 
/>
```

Is there a way how to configure this globally?

**Comment by laddi-netapp** [comment] 2021-12-08 13:05
Am experiencing the exact same problem after updating to Storybook 6.4.x, was working fine in 6.3.x but now I have to do this for every story.  Not really a huge problem but would be nice to just set it once in `preview.js` and be done with it.

**Comment by pixtron** [comment] 2021-12-22 15:27
Sorry for the late reply. This still works for me with storybook 6.4:

```
import { ArgsTable, Meta } from '@storybook/addon-docs';

<Meta
  title="My component"
  component="my-component"
/>

<ArgsTable of="my-component" />
```

Could you create a storybook reproduction repository by running `npx sb@next repro`, publish it in a public github repo and post the link to it here?

You might also try if the bug is fixed with version 6.4.0 of this module.

**Comment by laddi-netapp** [comment] 2021-12-22 15:38
You are right, I was using a different syntax:

```js
import { ArgsTable, Meta } from '@storybook/addon-docs';

<Meta
  title="My component"
  component="my-component"
/>

<ArgsTable story="My component" />
```

Can confirm that it works by using `of` instead of `story` for `ArgsTable`

**Comment by laddi-netapp** [comment] 2021-12-22 15:40
Ah, actually, the props are shown correctly but don't activate `addon-docs` for me in `Docs` view, works in `Canvas`, though...

Updated: Also tested with `6.4.0` with the same results.

**Comment by pixtron** [comment] 2021-12-22 20:40
@laddi-netapp  Could you provide a repo where i can reproduce the issue? Just create one with `npx sb@next repro` and push to github please.

**Comment by pixtron** [comment] 2022-02-05 13:17
See this comment: [#11](https://github.com/pixtron/storybook-addon-docs-stencil/issues/11#issuecomment-1030622917)

**Closed as completed by pixtron** 2022-02-05 13:17 UTC
