### ISSUE TITLE
Component not rendering

### ISSUE THREAD

**Issue by codewithtushar** [pixtron/storybook-addon-docs-stencil#10] opened 2022-01-18 21:35 UTC
**Describe the bug**
Not working for me
**Steps to Reproduce**
Followed steps from Readme

**Repro**

**Expected behavior**
docs.json is getting generated.

below is my story for my-component (generated by stencil)

export default {
    title: 'My Components',
    component: 'my-component',
};

cant see component in the UI
![image](https://user-images.githubusercontent.com/48051351/150021706-20623487-dcc7-4d44-92a8-23b6bef1b284.png)

it works when i try to add below it works

export default {
    title: 'My Components',
    component: 'my-component',
};
 
export const Default = args => {
  return `<my-component first="Test"></my-component>`;
};

![image](https://user-images.githubusercontent.com/48051351/150022310-93fd5bce-4015-48bf-b7ce-9c0f1d4b38c8.png)

**System**
Please paste the results of `npx sb@next info` here.
"@pxtrn/storybook-addon-docs-stencil": "^6.4.0",
    "@storybook/addon-essentials": "^6.4.13",
    "@storybook/addon-links": "^6.4.13",
    "@storybook/html": "^6.4.13",
**Additional context**
below is the folder structure i'm having 
![image](https://user-images.githubusercontent.com/48051351/150022400-27c8432e-dda3-4b9d-a7f2-03d0abee33ed.png)

**Comment by chrisajohn80** [comment] 2022-01-27 22:08
I am having a similar issue.  In addition, when I change controls it does not update the canvas.  Same issue in the "Docs" section.

Thanks so much for writing this!  If we could get it fully functioning it would really help me and my team.

**Comment by pixtron** [comment] 2022-02-05 12:18
Thank you for your issue. Unfortunately i can't reproduce your issue, therefore i will close it for now. If you still think you found a bug please open a new issue and provide a public github repo with a full example of your storybook/stencil setup, demo components and a detailed step by step description how the issue can be reproduced.

This module is not about rendering stencil components in storybook, and you won't ever need this module to render stencil components in storybook. This module solely parses stencils doc.json and configures the argTypes.  
If your components are not rendering at all in storybook, you need to make sure you include the stencil web components. This is out of scope of this module.

Probably your best bet is to search for "stencil storybook boilerplate" on google.

**Closed as completed by pixtron** 2022-02-05 12:18 UTC
Labels: bug
